version: '3.8'

services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
         args:
            - NEXTAUTH_URL=${NEXTAUTH_URL}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - DATABASE_URL=${DATABASE_URL}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
            - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
            - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
            - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
            - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
            - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
            - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

      ports:
         - '3000:3000'
      restart: always
      depends_on:
         - postgres
      environment:
         - NEXTAUTH_URL=${NEXTAUTH_URL}
         - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
         - DATABASE_URL=${DATABASE_URL}
         - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
         - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
         - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
         - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
         - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
         - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
         - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
         - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
         - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
         - SEED_DATABASE=${SEED_DATABASE:-false}
      networks:
         - app-network

   postgres:
      image: postgres:14-alpine
      ports:
         - '5432:5432'
      environment:
         - POSTGRES_USER=${POSTGRES_USER:-avnadmin}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-AVNS_Z-wdM2VyarurzKy88sa}
         - POSTGRES_DB=${POSTGRES_DB:-defaultdb}
      volumes:
         - postgres-data:/var/lib/postgresql/data
      networks:
         - app-network

   migration:
      build:
         context: .
         dockerfile: Dockerfile
         target: builder
      command: sh -c "cd /app && npx prisma migrate deploy && if [ \"$SEED_DATABASE\" = \"true\" ]; then npx prisma db seed; fi"
      depends_on:
         - postgres
      environment:
         - DATABASE_URL=${DATABASE_URL}
         - SEED_DATABASE=${SEED_DATABASE:-false}
      networks:
         - app-network

networks:
   app-network:
      driver: bridge

volumes:
   postgres-data:
