name: CI/CD Pipeline

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '22'
              cache: 'npm'

         - name: Install dependencies
           run: npm ci --legacy-peer-deps

         - name: Run linting
           run: npm run lint

   build:
      name: Build
      runs-on: ubuntu-latest
      needs: lint
      steps:
         - uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '22'
              cache: 'npm'

         - name: Install dependencies
           run: npm ci --legacy-peer-deps

         - name: Build application
           run: npm run build
           env:
              NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
              NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
              DATABASE_URL: ${{ secrets.DATABASE_URL }}
              GOOGLE_CLIENT_ID: ${{ secrets.GOOGLECLIENTID }}
              GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLECLIENTSECRET }}
              GITHUB_CLIENT_ID: ${{ secrets.GITHUBCLIENTID }}
              GITHUB_CLIENT_SECRET: ${{ secrets.GITHUBCLIENTSECRET }}
              #   UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
              #   UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
              NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
              CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
              CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

   docker-build:
      name: Build Docker Image
      runs-on: ubuntu-latest
      needs: build
      steps:
         - uses: actions/checkout@v3

         - name: Log into DockerHub
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

         - name: Build Docker image
           run: |
              docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .

         - name: Push Docker image to DockerHub
           run: |
              docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

   migrate:
      name: Database Migration
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/main'
      steps:
         - uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '22'
              cache: 'npm'

         - name: Install dependencies
           run: npm ci --legacy-peer-deps

         - name: Run migrations
           run: npx prisma migrate deploy
           env:
              DATABASE_URL: ${{ secrets.DATABASE_URL }}

   deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: migrate
      if: github.ref == 'refs/heads/main'
      steps:
         - uses: actions/checkout@v3

         - name: Deploy to Vercel
           uses: amondnet/vercel-action@v20
           with:
              zeit-token: ${{ secrets.VERCEL_TOKEN }}
              vercel-token: ${{ secrets.VERCEL_TOKEN }}
              vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
              vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
              vercel-args: '--prod'
