name: Create PR from develop to main

on:
   workflow_run:
      workflows: ['CI/CD Pipeline']
      types:
         - completed

jobs:
   create-pr:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repo
           uses: actions/checkout@v3
           with:
              repository: ${{ github.event.workflow_run.head_repository.full_name }}
              ref: ${{ github.event.workflow_run.head_branch }}

         - name: Create PR if it doesn't exist
           uses: actions/github-script@v7
           with:
              github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              script: |
                 const { data: pulls } = await github.rest.pulls.list({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   state: "open"
                 });

                 const prExists = pulls.some(pr => pr.head.ref === 'develop' && pr.base.ref === 'main');

                 if (!prExists) {
                   await github.rest.pulls.create({
                     owner: context.repo.owner,
                     repo: context.repo.repo,
                     title: "Merge develop into main",
                     head: "develop",
                     base: "main",
                     body: "Automatic PR after successful CI/CD pipeline."
                   });
                 } else {
                   console.log("PR already exists from develop to main.");
                 }
