name: Create Pull Request from Develop to Main

on:
   workflow_run:
      workflows: ['CI/CD Pipeline']
      types:
         - completed

jobs:
   create-pull-request:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repo
           uses: actions/checkout@v3

         - name: Set up Git
           run: |
              git config --global user.email "action@github.com"
              git config --global user.name "GitHub Action"

         - name: Create Pull Request
           uses: devops-infra/action-pull-request@v0.5.3
           with:
              github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              source_branch: develop # Use source_branch instead of head
              target_branch: main # Use target_branch instead of base
              title: 'Auto PR: Merge develop into main'
              body: |
                 This PR was automatically created by a GitHub Action
                 after a successful CI/CD run on the develop branch.
              allow_no_diff: false
